# Generated by Django 4.2.4 on 2023-09-11 13:27

from django.db import migrations, models
import todoapplogin_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapplogin_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, default=todoapplogin_app.models.one_week_hence, null=True
            ),
        ),
    ]
